version: "3.9"

services:
  notification-system:
    build:
      context: .
      dockerfile: Dockerfile
    image: notification-system:1.0.0
    container_name: notification-system
    ports:
      - "8098:8098"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: unless-stopped
