server:
  port: 8098
  servlet:
    context-path: /notification-system

## Values: HASHTABLE, MONGODB
database:
    strategy: HASHTABLE

notification:
  cron: "*/10 * * * * *"

---
spring:
  profiles:
    active: local

kafka:
  bootstrap-servers: localhost:9092
  topic:
    groupId: notification
    notification: topic-advertisement-notifications

---
spring:
  profiles:
    active: docker

kafka:
  bootstrap-servers: localhost:9092
  topic:
    groupId: notification
    notification: topic-advertisement-notifications
---
#spring:
 # data:
  #  mongodb:
   #   host: mongo-server
    #  port: 27017
     # database: advertisement-notification
      #username: admin
      #password: 1234
      #authentication-database: admin
      #auto-index-creation: true
