# =======================================
# DEFAULT CONFIG (applies to ALL profiles)
# =======================================
server:
  port: 8098
  servlet:
    context-path: /notification-system
  error:
    include-message: 'always'
    include-binding-errors: 'always'
    include-exception: 'false'

database:
  strategy: HASHTABLE

notification:
  cron: "*/5 * * * * *"

spring:
  profiles:
    active: local

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method
    path: /swagger.html

---
spring:
  config:
    activate:
      on-profile: local
kafka:
  bootstrap-servers: localhost:9092
  topic:
    groupId: notification
    notification: topic-advertisement-notifications
  consumer:
    group-id: notification
---
spring:
  config:
    activate:
      on-profile: docker
kafka:
  bootstrap-servers: kafka-server:29092
  topic:
    groupId: notification
    notification: topic-advertisement-notifications
  consumer:
    group-id: notification
---
